version: '2'
services:
  hello:
    build: ../
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SECRET_KEY_BASE=secret
      - MONGO_URL=mongodb://mongo:27017/hello
    links:
      - mongo
  mongo:
    build: ../docker-images/mongodb
    ports:
      - "27017:27017"
    restart: always
  jenkins:
    build: ../docker-images/jenkins
    ports:
      - "7070:8080"
    restart: always